name: my_friends_frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  provider: ^6.0.2
  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  email_validator: ^2.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

#  fonts:
#      - family: Oxygen
#        fonts:
#           - asset: assets/fonts/oxygen/Oxygen-Bold.ttf
#           - asset: assets/fonts/oxygen/Oxygen-Light.ttf
#           - asset: assets/fonts/oxygen/Oxygen-Regular.ttf
#      - family: Ubuntu
#        fonts:
#           - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
#           - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
#           - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
#           - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
#           - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
#           - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
#           - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
#           - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
